from typing import Dict, Any
from collections import OrderedDict
from backtrader import AutoOrderedDict

dbeyes_algoparams_1h = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                     {'switch': 0, 'threshold': 0.77,
                                      'power': 0.96, 'take_profit': 0.042,
                                      'stop_loss': 0.006}),
                                    ('model_aariHHo4HsXdYvN2cHe2e4',
                                     {'switch': 0, 'threshold': 0.5700000000000001,
                                      'power': 0.94, 'take_profit': 0.004,
                                      'stop_loss': 0.02}),
                                    ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                     {'switch': 0, 'threshold': 0.95,
                                      'power': 0.74, 'take_profit': 0.082,
                                      'stop_loss': 0.014000000000000002}),
                                    ('model_bKVWEgGNiG8XKubuDNpLLE',
                                     {'switch': 0, 'threshold': 0.7,
                                      'power': 0.8400000000000001, 'take_profit': 0.029,
                                      'stop_loss': 0.026}),
                                    ('model_CbVKn65FHoXuA56dgApNMv',
                                     {'switch': 0, 'threshold': 0.65,
                                      'power': 0.74, 'take_profit': 0.07300000000000001,
                                      'stop_loss': 0.003}),
                                    ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                     {'switch': 1, 'threshold': 0.7,
                                      'power': 0.8200000000000001, 'take_profit': 0.07,
                                      'stop_loss': 0.007}),
                                    ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                     {'switch': 0, 'threshold': 0.89,
                                      'power': 0.46, 'take_profit': 0.060000000000000005,
                                      'stop_loss': 0.026}),
                                    ('model_EypgLnn5tqaDcqr3jXdFMf',
                                     {'switch': 0, 'threshold': 0.52,
                                      'power': 0.48000000000000004, 'take_profit': 0.108,
                                      'stop_loss': 0.021}),
                                    ('model_L7ht6apekGCYoSdiqkifhA',
                                     {'switch': 0, 'threshold': 0.66,
                                      'power': 0.94, 'take_profit': 0.099,
                                      'stop_loss': 0.016}),
                                    ('model_LHBRpckZqt6dnGD2okdovx',
                                     {'switch': 0, 'threshold': 0.51, 'power': 0.8400000000000001,
                                      'take_profit': 0.089, 'stop_loss': 0.017}),
                                    ('model_M4WdNjWLcynEt6S7Gi3na4',
                                     {'switch': 1, 'threshold': 0.64,
                                      'power': 0.8200000000000001, 'take_profit': 0.061,
                                      'stop_loss': 0.025}),
                                    ('model_RQD9odDCf5jqxLoS27WYcJ',
                                     {'switch': 1, 'threshold': 0.63,
                                      'power': 0.8400000000000001, 'take_profit': 0.08700000000000001,
                                      'stop_loss': 0.023})])

dbeyessimv1_algoparams_1h = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                          {'switch': 0,
                                           'threshold': 0.74,
                                           'power': 0.94,
                                           'take_profit': 0.113,
                                           'stop_loss': 0.024}),
                                         ('model_aariHHo4HsXdYvN2cHe2e4',
                                          {'switch': 1,
                                           'threshold': 0.97,
                                           'power': 0.6000000000000001,
                                           'take_profit': 0.028,
                                           'stop_loss': 0.023}),
                                         ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                          {'switch': 0,
                                           'threshold': 0.8400000000000001,
                                           'power': 0.88,
                                           'take_profit': 0.061,
                                           'stop_loss': 0.018000000000000002}),
                                         ('model_bKVWEgGNiG8XKubuDNpLLE',
                                          {'switch': 0,
                                           'threshold': 0.75,
                                           'power': 0.98,
                                           'take_profit': 0.037000000000000005,
                                           'stop_loss': 0.022000000000000002}),
                                         ('model_CbVKn65FHoXuA56dgApNMv',
                                          {'switch': 1,
                                           'threshold': 0.65,
                                           'power': 0.88,
                                           'take_profit': 0.065,
                                           'stop_loss': 0.025}),
                                         ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                          {'switch': 0,
                                           'threshold': 0.53,
                                           'power': 0.92,
                                           'take_profit': 0.079,
                                           'stop_loss': 0.002}),
                                         ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                          {'switch': 1,
                                           'threshold': 0.66,
                                           'power': 0.8200000000000001,
                                           'take_profit': 0.053000000000000005,
                                           'stop_loss': 0.012}),
                                         ('model_EypgLnn5tqaDcqr3jXdFMf',
                                          {'switch': 1,
                                           'threshold': 0.65,
                                           'power': 0.62,
                                           'take_profit': 0.1,
                                           'stop_loss': 0.005}),
                                         ('model_L7ht6apekGCYoSdiqkifhA',
                                          {'switch': 0,
                                           'threshold': 0.7,
                                           'power': 0.66,
                                           'take_profit': 0.004,
                                           'stop_loss': 0.001}),
                                         ('model_LHBRpckZqt6dnGD2okdovx',
                                          {'switch': 1,
                                           'threshold': 0.9,
                                           'power': 0.8,
                                           'take_profit': 0.117,
                                           'stop_loss': 0.011}),
                                         ('model_M4WdNjWLcynEt6S7Gi3na4',
                                          {'switch': 0,
                                           'threshold': 0.8300000000000001,
                                           'power': 0.56,
                                           'take_profit': 0.032,
                                           'stop_loss': 0.008}),
                                         ('model_RQD9odDCf5jqxLoS27WYcJ',
                                          {'switch': 1,
                                           'threshold': 0.63,
                                           'power': 0.68,
                                           'take_profit': 0.030000000000000002,
                                           'stop_loss': 0.005}),
                                         ('minus',
                                          {'threshold': 5.39,
                                           'power': 0.97,
                                           'take_profit': 0.08,
                                           'stop_loss': 0.004}),
                                         ('plus',
                                          {'threshold': 0.55,
                                           'power': 1.0899999999999999,
                                           'take_profit': 0.08700000000000001,
                                           'stop_loss': 0.022000000000000002})])

dbeyessimv1_algoparams_1h_t40 = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                              {'switch': 0,
                                               'threshold': 0.8400000000000001,
                                               'power': 0.56,
                                               'take_profit': 0.011,
                                               'stop_loss': 0.018000000000000002}),
                                             ('model_aariHHo4HsXdYvN2cHe2e4',
                                              {'switch': 1,
                                               'threshold': 0.95,
                                               'power': 0.66,
                                               'take_profit': 0.081,
                                               'stop_loss': 0.011}),
                                             ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                              {'switch': 1,
                                               'threshold': 0.9299999999999999,
                                               'power': 0.8200000000000001,
                                               'take_profit': 0.079,
                                               'stop_loss': 0.014000000000000002}),
                                             ('model_bKVWEgGNiG8XKubuDNpLLE',
                                              {'switch': 1,
                                               'threshold': 0.5800000000000001,
                                               'power': 0.8400000000000001,
                                               'take_profit': 0.113,
                                               'stop_loss': 0.018000000000000002}),
                                             ('model_CbVKn65FHoXuA56dgApNMv',
                                              {'switch': 0,
                                               'threshold': 0.8600000000000001,
                                               'power': 0.6000000000000001,
                                               'take_profit': 0.117,
                                               'stop_loss': 0.021}),
                                             ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                              {'switch': 0,
                                               'threshold': 0.53,
                                               'power': 0.8400000000000001,
                                               'take_profit': 0.002,
                                               'stop_loss': 0.019000000000000003}),
                                             ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                              {'switch': 0,
                                               'threshold': 0.71,
                                               'power': 0.52,
                                               'take_profit': 0.109,
                                               'stop_loss': 0.018000000000000002}),
                                             ('model_EypgLnn5tqaDcqr3jXdFMf',
                                              {'switch': 0,
                                               'threshold': 0.9299999999999999,
                                               'power': 0.54,
                                               'take_profit': 0.014000000000000002,
                                               'stop_loss': 0.012}),
                                             ('model_L7ht6apekGCYoSdiqkifhA',
                                              {'switch': 0,
                                               'threshold': 0.8400000000000001,
                                               'power': 0.9,
                                               'take_profit': 0.114,
                                               'stop_loss': 0.024}),
                                             ('model_LHBRpckZqt6dnGD2okdovx',
                                              {'switch': 1,
                                               'threshold': 0.97,
                                               'power': 0.62,
                                               'take_profit': 0.067,
                                               'stop_loss': 0.006}),
                                             ('model_M4WdNjWLcynEt6S7Gi3na4',
                                              {'switch': 1,
                                               'threshold': 0.61,
                                               'power': 0.78,
                                               'take_profit': 0.095,
                                               'stop_loss': 0.02}),
                                             ('model_RQD9odDCf5jqxLoS27WYcJ',
                                              {'switch': 1,
                                               'threshold': 0.5800000000000001,
                                               'power': 0.8400000000000001,
                                               'take_profit': 0.11800000000000001,
                                               'stop_loss': 0.011}),
                                             ('minus',
                                              {'threshold': 0.55,
                                               'power': 0.49,
                                               'take_profit': 0.089,
                                               'stop_loss': 0.02}),
                                             ('plus',
                                              {'threshold': 0.51,
                                               'power': 0.37,
                                               'take_profit': 0.085,
                                               'stop_loss': 0.023})])

dbeyessimv1t15_algoparams = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                          {'switch': 0,
                                           'threshold': 0.65,
                                           'power': 0.76,
                                           'take_profit': 0.057,
                                           'stop_loss': 0.001}),
                                         ('model_aariHHo4HsXdYvN2cHe2e4',
                                          {'switch': 1,
                                           'threshold': 0.76,
                                           'power': 0.96,
                                           'take_profit': 0.12,
                                           'stop_loss': 0.002}),
                                         ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                          {'switch': 1,
                                           'threshold': 0.51,
                                           'power': 0.76,
                                           'take_profit': 0.056,
                                           'stop_loss': 0.012}),
                                         ('model_bKVWEgGNiG8XKubuDNpLLE',
                                          {'switch': 1,
                                           'threshold': 0.91,
                                           'power': 0.96,
                                           'take_profit': 0.066,
                                           'stop_loss': 0.025}),
                                         ('model_CbVKn65FHoXuA56dgApNMv',
                                          {'switch': 1,
                                           'threshold': 0.51,
                                           'power': 0.8400000000000001,
                                           'take_profit': 0.081,
                                           'stop_loss': 0.023}),
                                         ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                          {'switch': 0,
                                           'threshold': 0.89,
                                           'power': 0.78,
                                           'take_profit': 0.10200000000000001,
                                           'stop_loss': 0.015}),
                                         ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                          {'switch': 1,
                                           'threshold': 0.53,
                                           'power': 0.46,
                                           'take_profit': 0.064,
                                           'stop_loss': 0.003}),
                                         ('model_EypgLnn5tqaDcqr3jXdFMf',
                                          {'switch': 0,
                                           'threshold': 0.51,
                                           'power': 0.8,
                                           'take_profit': 0.055,
                                           'stop_loss': 0.012}),
                                         ('model_L7ht6apekGCYoSdiqkifhA',
                                          {'switch': 0,
                                           'threshold': 0.95,
                                           'power': 0.8,
                                           'take_profit': 0.081,
                                           'stop_loss': 0.014000000000000002}),
                                         ('model_LHBRpckZqt6dnGD2okdovx',
                                          {'switch': 1,
                                           'threshold': 0.7,
                                           'power': 0.9,
                                           'take_profit': 0.031,
                                           'stop_loss': 0.02}),
                                         ('model_M4WdNjWLcynEt6S7Gi3na4',
                                          {'switch': 0,
                                           'threshold': 0.66,
                                           'power': 0.62,
                                           'take_profit': 0.089,
                                           'stop_loss': 0.003}),
                                         ('model_RQD9odDCf5jqxLoS27WYcJ',
                                          {'switch': 1,
                                           'threshold': 0.5800000000000001,
                                           'power': 0.5800000000000001,
                                           'take_profit': 0.059000000000000004,
                                           'stop_loss': 0.006}),
                                         ('minus',
                                          {'threshold': 0.99,
                                           'power': 1.39,
                                           'take_profit': 0.061,
                                           'stop_loss': 0.021}),
                                         ('plus',
                                          {'threshold': 1.1099999999999999,
                                           'power': 1.81,
                                           'take_profit': 0.083,
                                           'stop_loss': 0.019000000000000003})])

dbeyessimv1t15_algoparams_131087 = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                                 {'switch': 0,
                                                  'threshold': 0.8300000000000001,
                                                  'power': 0.88,
                                                  'take_profit': 0.095,
                                                  'stop_loss': 0.010000000000000002}),
                                                ('model_aariHHo4HsXdYvN2cHe2e4',
                                                 {'switch': 1,
                                                  'threshold': 0.9,
                                                  'power': 0.46,
                                                  'take_profit': 0.12,
                                                  'stop_loss': 0.024}),
                                                ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                                 {'switch': 0,
                                                  'threshold': 0.77,
                                                  'power': 0.8400000000000001,
                                                  'take_profit': 0.057,
                                                  'stop_loss': 0.005}),
                                                ('model_bKVWEgGNiG8XKubuDNpLLE',
                                                 {'switch': 1,
                                                  'threshold': 0.8,
                                                  'power': 0.54,
                                                  'take_profit': 0.115,
                                                  'stop_loss': 0.022000000000000002}),
                                                ('model_CbVKn65FHoXuA56dgApNMv',
                                                 {'switch': 1,
                                                  'threshold': 0.51,
                                                  'power': 0.8400000000000001,
                                                  'take_profit': 0.063,
                                                  'stop_loss': 0.008}),
                                                ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                                 {'switch': 1,
                                                  'threshold': 0.88,
                                                  'power': 0.8200000000000001,
                                                  'take_profit': 0.111,
                                                  'stop_loss': 0.012}),
                                                ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                                 {'switch': 1,
                                                  'threshold': 0.53,
                                                  'power': 0.88,
                                                  'take_profit': 0.068,
                                                  'stop_loss': 0.024}),
                                                ('model_EypgLnn5tqaDcqr3jXdFMf',
                                                 {'switch': 0,
                                                  'threshold': 0.99,
                                                  'power': 0.6000000000000001,
                                                  'take_profit': 0.111,
                                                  'stop_loss': 0.002}),
                                                ('model_L7ht6apekGCYoSdiqkifhA',
                                                 {'switch': 0,
                                                  'threshold': 0.71,
                                                  'power': 0.78,
                                                  'take_profit': 0.109,
                                                  'stop_loss': 0.010000000000000002}),
                                                ('model_LHBRpckZqt6dnGD2okdovx',
                                                 {'switch': 0,
                                                  'threshold': 0.9,
                                                  'power': 0.94,
                                                  'take_profit': 0.068,
                                                  'stop_loss': 0.026}),
                                                ('model_M4WdNjWLcynEt6S7Gi3na4',
                                                 {'switch': 0,
                                                  'threshold': 0.81,
                                                  'power': 0.5800000000000001,
                                                  'take_profit': 0.061,
                                                  'stop_loss': 0.014000000000000002}),
                                                ('model_RQD9odDCf5jqxLoS27WYcJ',
                                                 {'switch': 1,
                                                  'threshold': 0.87,
                                                  'power': 0.68,
                                                  'take_profit': 0.061,
                                                  'stop_loss': 0.003}),
                                                ('minus',
                                                 {'threshold': 0.55,
                                                  'power': 0.73,
                                                  'take_profit': 0.11900000000000001,
                                                  'stop_loss': 0.002}),
                                                ('plus',
                                                 {'threshold': 0.51,
                                                  'power': 0.37,
                                                  'take_profit': 0.094,
                                                  'stop_loss': 0.023})])
dbeyessimv1t15_algoparams_40326 = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                                {'switch': 1,
                                                 'threshold': 0.71,
                                                 'power': 0.5800000000000001,
                                                 'take_profit': 0.094,
                                                 'stop_loss': 0.016}),
                                               ('model_aariHHo4HsXdYvN2cHe2e4',
                                                {'switch': 1,
                                                 'threshold': 0.76,
                                                 'power': 0.9,
                                                 'take_profit': 0.030000000000000002,
                                                 'stop_loss': 0.026}),
                                               ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                                {'switch': 1,
                                                 'threshold': 0.62,
                                                 'power': 0.76,
                                                 'take_profit': 0.075,
                                                 'stop_loss': 0.025}),
                                               ('model_bKVWEgGNiG8XKubuDNpLLE',
                                                {'switch': 0,
                                                 'threshold': 0.92,
                                                 'power': 0.94,
                                                 'take_profit': 0.076,
                                                 'stop_loss': 0.018000000000000002}),
                                               ('model_CbVKn65FHoXuA56dgApNMv',
                                                {'switch': 1,
                                                 'threshold': 0.52,
                                                 'power': 0.64,
                                                 'take_profit': 0.081,
                                                 'stop_loss': 0.006}),
                                               ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                                {'switch': 0,
                                                 'threshold': 0.53,
                                                 'power': 0.5800000000000001,
                                                 'take_profit': 0.032,
                                                 'stop_loss': 0.015}),
                                               ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                                {'switch': 1,
                                                 'threshold': 0.54,
                                                 'power': 0.6000000000000001,
                                                 'take_profit': 0.064,
                                                 'stop_loss': 0.003}),
                                               ('model_EypgLnn5tqaDcqr3jXdFMf',
                                                {'switch': 0,
                                                 'threshold': 0.91,
                                                 'power': 0.96,
                                                 'take_profit': 0.008,
                                                 'stop_loss': 0.012}),
                                               ('model_L7ht6apekGCYoSdiqkifhA',
                                                {'switch': 0,
                                                 'threshold': 0.95,
                                                 'power': 0.56,
                                                 'take_profit': 0.038,
                                                 'stop_loss': 0.026}),
                                               ('model_LHBRpckZqt6dnGD2okdovx',
                                                {'switch': 1,
                                                 'threshold': 0.7,
                                                 'power': 0.9,
                                                 'take_profit': 0.116,
                                                 'stop_loss': 0.014000000000000002}),
                                               ('model_M4WdNjWLcynEt6S7Gi3na4',
                                                {'switch': 0,
                                                 'threshold': 0.66,
                                                 'power': 0.68,
                                                 'take_profit': 0.032,
                                                 'stop_loss': 0.003}),
                                               ('model_RQD9odDCf5jqxLoS27WYcJ',
                                                {'switch': 1,
                                                 'threshold': 0.63,
                                                 'power': 0.5800000000000001,
                                                 'take_profit': 0.106,
                                                 'stop_loss': 0.006}),
                                               ('minus',
                                                {'threshold': 0.99,
                                                 'power': 1.39,
                                                 'take_profit': 0.07,
                                                 'stop_loss': 0.010000000000000002}),
                                               ('plus',
                                                {'threshold': 1.1099999999999999,
                                                 'power': 1.5699999999999998,
                                                 'take_profit': 0.083,
                                                 'stop_loss': 0.02})])

dbeyessimv1t30_algoparams_59573 = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                                {'switch': 1,
                                                 'threshold': 0.77,
                                                 'power': 0.3,
                                                 'take_profit': 0.062,
                                                 'stop_loss': 0.016}),
                                               ('model_aariHHo4HsXdYvN2cHe2e4',
                                                {'switch': 1,
                                                 'threshold': 0.62,
                                                 'power': 0.32999999999999996,
                                                 'take_profit': 0.089,
                                                 'stop_loss': 0.02}),
                                               ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                                {'switch': 1,
                                                 'threshold': 0.54,
                                                 'power': 0.36,
                                                 'take_profit': 0.10500000000000001,
                                                 'stop_loss': 0.007}),
                                               ('model_bKVWEgGNiG8XKubuDNpLLE',
                                                {'switch': 0,
                                                 'threshold': 0.65,
                                                 'power': 0.51,
                                                 'take_profit': 0.07100000000000001,
                                                 'stop_loss': 0.003}),
                                               ('model_CbVKn65FHoXuA56dgApNMv',
                                                {'switch': 1,
                                                 'threshold': 0.42,
                                                 'power': 0.44999999999999996,
                                                 'take_profit': 0.004,
                                                 'stop_loss': 0.001}),
                                               ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                                {'switch': 1,
                                                 'threshold': 0.8600000000000001,
                                                 'power': 0.42,
                                                 'take_profit': 0.014000000000000002,
                                                 'stop_loss': 0.010000000000000002}),
                                               ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                                {'switch': 1,
                                                 'threshold': 0.9299999999999999,
                                                 'power': 0.42,
                                                 'take_profit': 0.08600000000000001,
                                                 'stop_loss': 0.002}),
                                               ('model_EypgLnn5tqaDcqr3jXdFMf',
                                                {'switch': 0,
                                                 'threshold': 0.95,
                                                 'power': 0.42,
                                                 'take_profit': 0.083,
                                                 'stop_loss': 0.026}),
                                               ('model_L7ht6apekGCYoSdiqkifhA',
                                                {'switch': 0,
                                                 'threshold': 0.66,
                                                 'power': 0.6,
                                                 'take_profit': 0.045,
                                                 'stop_loss': 0.012}),
                                               ('model_LHBRpckZqt6dnGD2okdovx',
                                                {'switch': 0,
                                                 'threshold': 0.9,
                                                 'power': 0.6599999999999999,
                                                 'take_profit': 0.026000000000000002,
                                                 'stop_loss': 0.025}),
                                               ('model_M4WdNjWLcynEt6S7Gi3na4',
                                                {'switch': 0,
                                                 'threshold': 0.8600000000000001,
                                                 'power': 0.6599999999999999,
                                                 'take_profit': 0.076,
                                                 'stop_loss': 0.011}),
                                               ('model_RQD9odDCf5jqxLoS27WYcJ',
                                                {'switch': 1,
                                                 'threshold': 0.8200000000000001,
                                                 'power': 0.42,
                                                 'take_profit': 0.021,
                                                 'stop_loss': 0.009000000000000001}),
                                               ('minus',
                                                {'threshold': 0.91,
                                                 'power': 0.60,
                                                 'take_profit': 0.076,
                                                 'stop_loss': 0.008}),
                                               ('plus',
                                                {'threshold': 0.51,
                                                 'power': 0.400,
                                                 'take_profit': 0.078,
                                                 'stop_loss': 0.024})])

dbeyessimv1t30_algoparams_123966 = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                                 {'switch': 1,
                                                  'threshold': 0.8200000000000001,
                                                  'power': 0.3,
                                                  'take_profit': 0.107,
                                                  'stop_loss': 0.009000000000000001}),
                                                ('model_aariHHo4HsXdYvN2cHe2e4',
                                                 {'switch': 1,
                                                  'threshold': 0.91,
                                                  'power': 0.36,
                                                  'take_profit': 0.10300000000000001,
                                                  'stop_loss': 0.017}),
                                                ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                                 {'switch': 1,
                                                  'threshold': 0.69,
                                                  'power': 0.36,
                                                  'take_profit': 0.10200000000000001,
                                                  'stop_loss': 0.016}),
                                                ('model_bKVWEgGNiG8XKubuDNpLLE',
                                                 {'switch': 0,
                                                  'threshold': 0.54,
                                                  'power': 0.32999999999999996,
                                                  'take_profit': 0.049,
                                                  'stop_loss': 0.023}),
                                                ('model_CbVKn65FHoXuA56dgApNMv',
                                                 {'switch': 1,
                                                  'threshold': 0.51,
                                                  'power': 0.32999999999999996,
                                                  'take_profit': 0.046,
                                                  'stop_loss': 0.023}),
                                                ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                                 {'switch': 1,
                                                  'threshold': 0.7,
                                                  'power': 0.3,
                                                  'take_profit': 0.11900000000000001,
                                                  'stop_loss': 0.017}),
                                                ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                                 {'switch': 0,
                                                  'threshold': 0.53,
                                                  'power': 0.39,
                                                  'take_profit': 0.094,
                                                  'stop_loss': 0.016}),
                                                ('model_EypgLnn5tqaDcqr3jXdFMf',
                                                 {'switch': 0,
                                                  'threshold': 0.55,
                                                  'power': 0.39,
                                                  'take_profit': 0.027000000000000003,
                                                  'stop_loss': 0.002}),
                                                ('model_L7ht6apekGCYoSdiqkifhA',
                                                 {'switch': 0,
                                                  'threshold': 0.53,
                                                  'power': 0.3,
                                                  'take_profit': 0.08600000000000001,
                                                  'stop_loss': 0.018000000000000002}),
                                                ('model_LHBRpckZqt6dnGD2okdovx',
                                                 {'switch': 1,
                                                  'threshold': 0.76,
                                                  'power': 0.36,
                                                  'take_profit': 0.039,
                                                  'stop_loss': 0.018000000000000002}),
                                                ('model_M4WdNjWLcynEt6S7Gi3na4',
                                                 {'switch': 0,
                                                  'threshold': 0.8200000000000001,
                                                  'power': 0.36,
                                                  'take_profit': 0.101,
                                                  'stop_loss': 0.023}),
                                                ('model_RQD9odDCf5jqxLoS27WYcJ',
                                                 {'switch': 0,
                                                  'threshold': 0.8300000000000001,
                                                  'power': 0.36,
                                                  'take_profit': 0.089,
                                                  'stop_loss': 0.002}),
                                                ('minus',
                                                 {'threshold': 0.67,
                                                  'power': 0.33320000000000005,
                                                  'take_profit': 0.115,
                                                  'stop_loss': 0.023}),
                                                ('plus',
                                                 {'threshold': 0.51,
                                                  'power': 0.3998,
                                                  'take_profit': 0.076,
                                                  'stop_loss': 0.021})])
dbeyessimt5d15_algoparams_40326 = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                                {'switch': 1,
                                                 'threshold': 0.71,
                                                 'power': 0.5800000000000001,
                                                 'take_profit': 0.094,
                                                 'stop_loss': 0.016}),
                                               ('model_aariHHo4HsXdYvN2cHe2e4',
                                                {'switch': 1,
                                                 'threshold': 0.76,
                                                 'power': 0.9,
                                                 'take_profit': 0.030000000000000002,
                                                 'stop_loss': 0.026}),
                                               ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                                {'switch': 1,
                                                 'threshold': 0.62,
                                                 'power': 0.76,
                                                 'take_profit': 0.075,
                                                 'stop_loss': 0.025}),
                                               ('model_bKVWEgGNiG8XKubuDNpLLE',
                                                {'switch': 0,
                                                 'threshold': 0.92,
                                                 'power': 0.94,
                                                 'take_profit': 0.076,
                                                 'stop_loss': 0.018000000000000002}),
                                               ('model_CbVKn65FHoXuA56dgApNMv',
                                                {'switch': 1,
                                                 'threshold': 0.52,
                                                 'power': 0.64,
                                                 'take_profit': 0.081,
                                                 'stop_loss': 0.006}),
                                               ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                                {'switch': 0,
                                                 'threshold': 0.53,
                                                 'power': 0.5800000000000001,
                                                 'take_profit': 0.032,
                                                 'stop_loss': 0.015}),
                                               ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                                {'switch': 1,
                                                 'threshold': 0.54,
                                                 'power': 0.6000000000000001,
                                                 'take_profit': 0.064,
                                                 'stop_loss': 0.003}),
                                               ('model_EypgLnn5tqaDcqr3jXdFMf',
                                                {'switch': 0,
                                                 'threshold': 0.91,
                                                 'power': 0.96,
                                                 'take_profit': 0.008,
                                                 'stop_loss': 0.012}),
                                               ('model_L7ht6apekGCYoSdiqkifhA',
                                                {'switch': 0,
                                                 'threshold': 0.95,
                                                 'power': 0.56,
                                                 'take_profit': 0.038,
                                                 'stop_loss': 0.026}),
                                               ('model_LHBRpckZqt6dnGD2okdovx',
                                                {'switch': 1,
                                                 'threshold': 0.7,
                                                 'power': 0.9,
                                                 'take_profit': 0.116,
                                                 'stop_loss': 0.014000000000000002}),
                                               ('model_M4WdNjWLcynEt6S7Gi3na4',
                                                {'switch': 0,
                                                 'threshold': 0.66,
                                                 'power': 0.68,
                                                 'take_profit': 0.032,
                                                 'stop_loss': 0.003}),
                                               ('model_RQD9odDCf5jqxLoS27WYcJ',
                                                {'switch': 1,
                                                 'threshold': 0.63,
                                                 'power': 0.5800000000000001,
                                                 'take_profit': 0.106,
                                                 'stop_loss': 0.006}),
                                               ('minus',
                                                {'threshold': 0.99,
                                                 'power': 1.39,
                                                 'take_profit': 0.07,
                                                 'stop_loss': 0.010000000000000002}),
                                               ('plus',
                                                {'threshold': 1.1099999999999999,
                                                 'power': 1.5699999999999998,
                                                 'take_profit': 0.083,
                                                 'stop_loss': 0.02})])

dbeyessimt5d15_algoparams_232552 = OrderedDict([('model_2WQiArtMvsZ2J9ffjRdiu3',
                                                 {'switch': 1,
                                                  'threshold': 0.53,
                                                  'power': 0.39,
                                                  'take_profit': 0.060000000000000005,
                                                  'stop_loss': 0.019000000000000003}),
                                                ('model_aariHHo4HsXdYvN2cHe2e4',
                                                 {'switch': 1,
                                                  'threshold': 0.99,
                                                  'power': 0.32999999999999996,
                                                  'take_profit': 0.106,
                                                  'stop_loss': 0.007}),
                                                ('model_Ap7ETFJdQ5gEzSrQTHJ6nt',
                                                 {'switch': 1,
                                                  'threshold': 0.51,
                                                  'power': 0.32999999999999996,
                                                  'take_profit': 0.08,
                                                  'stop_loss': 0.001}),
                                                ('model_bKVWEgGNiG8XKubuDNpLLE',
                                                 {'switch': 1,
                                                  'threshold': 0.78,
                                                  'power': 0.36,
                                                  'take_profit': 0.109,
                                                  'stop_loss': 0.003}),
                                                ('model_CbVKn65FHoXuA56dgApNMv',
                                                 {'switch': 1,
                                                  'threshold': 0.53,
                                                  'power': 0.36,
                                                  'take_profit': 0.026000000000000002,
                                                  'stop_loss': 0.026}),
                                                ('model_DEJ9zMtFJiCZq3eUEdU3gn',
                                                 {'switch': 1,
                                                  'threshold': 0.79,
                                                  'power': 0.36,
                                                  'take_profit': 0.016,
                                                  'stop_loss': 0.005}),
                                                ('model_EQ2L9YqZPZE8ReQSYTKA3m',
                                                 {'switch': 1,
                                                  'threshold': 0.55,
                                                  'power': 0.32999999999999996,
                                                  'take_profit': 0.018000000000000002,
                                                  'stop_loss': 0.012}),
                                                ('model_EypgLnn5tqaDcqr3jXdFMf',
                                                 {'switch': 1,
                                                  'threshold': 0.89,
                                                  'power': 0.36,
                                                  'take_profit': 0.112,
                                                  'stop_loss': 0.004}),
                                                ('model_L7ht6apekGCYoSdiqkifhA',
                                                 {'switch': 0,
                                                  'threshold': 0.69,
                                                  'power': 0.39,
                                                  'take_profit': 0.009000000000000001,
                                                  'stop_loss': 0.024}),
                                                ('model_LHBRpckZqt6dnGD2okdovx',
                                                 {'switch': 1,
                                                  'threshold': 0.9299999999999999,
                                                  'power': 0.32999999999999996,
                                                  'take_profit': 0.08800000000000001,
                                                  'stop_loss': 0.001}),
                                                ('model_M4WdNjWLcynEt6S7Gi3na4',
                                                 {'switch': 0,
                                                  'threshold': 0.69,
                                                  'power': 0.36,
                                                  'take_profit': 0.07200000000000001,
                                                  'stop_loss': 0.009000000000000001}),
                                                ('model_RQD9odDCf5jqxLoS27WYcJ',
                                                 {'switch': 1,
                                                  'threshold': 0.62,
                                                  'power': 0.36,
                                                  'take_profit': 0.11900000000000001,
                                                  'stop_loss': 0.024}),
                                                ('minus',
                                                 {'threshold': 0.71,
                                                  'power': 0.2333,
                                                  'take_profit': 0.08700000000000001,
                                                  'stop_loss': 0.009000000000000001}),
                                                ('plus',
                                                 {'threshold': 0.55,
                                                  'power': 0.2,
                                                  'take_profit': 0.093,
                                                  'stop_loss': 0.013000000000000001})])
